version: "3.7"
services:
  web:
    image: nginx:1.19.4-alpine
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    volumes:
    - ./index.html:/var/www/index.html
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./testdomain.key:/etc/nginx/ssl/private/testdomain.key
    - ./testdomain.local.crt:/etc/nginx/ssl/cert/testdomain.local.crt
  php:
    image: php:7.2-fpm
    volumes:
      - ./:/var/www
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: testpass
    ports:
      - 3306:3306
    volumes:
      - /myproject:/var/lib/mysql